name: Create PR for new WPGatsby PR
on: 
  workflow_dispatch:
    inputs:
      remoteref:
        required: true
        default: "default-branch"
        description: "the incoming new ref from wp-gatsby repository"
jobs:
  version:
    name: Run WPGatsby PR with branch
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: "Replace version in file"
        # printf to escape slashes in strings
        run: sed -ir 's/^WPGATSBY_VERSION.*/WPGATSBY_VERSION=$(printf "%q" "${{ github.event.inputs.remoteref }}")/' test-site/.env.plugins
      - name: "Create WPGatsby PR"
        uses: technote-space/create-pr-action@v2
        with:
          COMMIT_MESSAGE: "ci: test with wpgatsby PR ${{ github.event.inputs.remoteref }}"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "example@example.com"
          PR_BRANCH_NAME: "chore/test-wp-gatsby-${{ github.event.inputs.remoteref }}"
          PR_TITLE: "ci: test with wpgatsby branch ${{ github.event.inputs.remoteref }}"
