on: [workflow_dispatch]
jobs:
  version:
    name: Run WPGatsby PR with branch
    runs-on: ubuntu-16.04
    steps:
      - name: "Replace version in file"
        # TODO: use inputs.remoref until we understand how to dispatch a event.ref that doesn't exist yet
        run: sed -ir 's/^WPGATSBY_VERSION.*/WPGATSBY_VERSION=${{ github.event.inputs.remoteref }}/' test-site/.env.plugins
      - name: "Create WPGatsby PR"
        uses: technote-space/create-pr-action@v2
        with:
          COMMIT_MESSAGE: "ci: test with wpgatsby PR ${{ github.event.inputs.remoteref }}"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "example@example.com"
          PR_BRANCH_NAME: "chore/test-wp-gatsby-${{ github.event.inputs.remoteref }}"
          PR_TITLE: "ci: test with wpgatsby branch ${{ github.event.inputs.remoteref }}"
